### ISSUE TITLE
Add GA4GH GKS normalization notebook

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/gnomad-frequency-report#10] opened 2023-05-30 19:32 UTC

**Comment by theferrit32** [comment] 2023-06-01 01:47
My current plan here is to have a jupyter notebook that will automate loading and starting a seqrepo rest server inside a hail dataproc cluster and configuring vrs-python to use it, and will enable doing live normalizations of simple alleles from a hail table. The vrs-python calls on the hail workers will communicate with the seqrepo rest service on the dataproc master node. Depending on the specifics of what alleles are in the hail table and how big the table is, doing this through hail's parallel computation of expression fields might run into synchronization related exceptions in the seqrepo rest service.

https://github.com/biocommons/seqrepo-rest-service/issues/12

**Comment by larrybabb** [comment] 2023-06-12 18:39
This is a duplicate of https://app.zenhub.com/workspaces/genegraphdxclinvar-60340fb9898dae001107e94e/issues/gh/ga4gh/va-spec/102

**Closed as completed** 2023-06-15 15:25 UTC
